[phases.setup]
nixPkgs = ["php83", "php83Extensions.intl", "php83Extensions.zip", "php83Extensions.pdo_mysql"]

[phases.build]
cmds = ["composer update --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"
